## Taller de Ejemplo

## EJECUTA ESTA CELDA PARA AUTENTICARTE CON TU CUENTA DE GMAIL

In [3]:
!pip install -q oauth2client==1.5.2
from mooclib import *
import sys, inspect, urllib
sys.path.append("./utils/student_function/")
html, auth_code, userinfo = google_authenticate(PORT_NUMBER=8080)
html

CLICK ON THIS LINK TO AUTHENTICATE WITH YOUR GMAIL ACCOUNT
https://accounts.google.com/o/oauth2/auth?client_id=486275613361-7nk9ktukfcfjevfoe3tamjp0pmbjmprs.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080&scope=profile+email&access_type=offline&response_type=code
waiting for authentication ...
authentication succeeded


### Ejercicio 1: Suma dos matrices

Completa la función `suma_matrices` para que, dadas dos arrays numpy cualquiera devuelva la suma elemento a elemento.

#### Ejemplo de ejecución

    > s = np.array([1,2,3])
    > t = np.array([4,5,6])
    > suma_matrices(s,t)
    
      [5 7 9]
     

In [1]:
%%writefile ./utils/student_function/PS00_01.py

import numpy as np

def suma_matrices(a,b):
    result = a+b
    return result


Writing ./utils/student_function/PS00_01.py


comprueba manualmente tu código

In [4]:
import PS00_01 as st
from importlib import reload; reload(st)
import numpy as np
a = np.random.randint(10, size=(3,2))
b = np.random.randint(10, size=(3,2))
print (a)
print (b)
print (st.suma_matrices(a,b))

[[5 2]
 [1 6]
 [2 6]]
[[0 1]
 [4 5]
 [6 4]]
[[ 5  3]
 [ 5 11]
 [ 8 10]]


#### comprueba tu código con el corrector automático

In [5]:
!./run CHECK_SOLUTION PS00_01

checking your code with 100 random calls
** CORRECTO **
evaluation result 5.0


#### registra tu solución en línea

In [6]:
!./run SUBMIT_SOLUTION PS00_01

connecting ... registering submission for sebastian.ruiz8@udea.edu.co ...
no config found for section PS00, allowing all submissions
your submissions sheet is https://docs.google.com/spreadsheets/d/1WaK6Gr9sKYog5B6r3UnFKCNRUOte1AwPbjkDQg5r3kI
checking your code with 100 random calls
** CORRECTO **
----
evaluation result 5.0 , submission registered
